/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Brave_Iruka (https://sketchfab.com/Brave_Iruka)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/thermal-katana-remake-97566e9dafc14a9d88053baf703d332f
title: Thermal katana remake
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const [scale, setScale] = useState(2);
  const { nodes, materials } = useGLTF("/katana.gltf");
  useEffect(() => {
    const checkScale = () => {
      if (window.innerWidth < 768) {
        setScale(1);
      }
    };
    checkScale();
  }, [scale]);
  return (
    <group ref={group} {...props} dispose={null} scale={scale}>
      <group position={[0, -2.5, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group
            position={[-5.26, 0, 2.49]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[3.14, 0.11, 0.04]}
          >
            <mesh
              geometry={nodes.blade1_lambert5_0.geometry}
              material={materials.lambert5}
            />
          </group>
          <group
            position={[0.9, 0, 2.63]}
            rotation={[Math.PI / 2, 0, -0.08]}
            scale={[0.26, 0.13, 0.08]}
          >
            <mesh
              geometry={nodes.support_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[2.61, 0, 2.39]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.11}
          >
            <mesh
              geometry={nodes.pCube5_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[-2.19, 0, 2.91]}
            rotation={[Math.PI / 2, 0, -0.12]}
            scale={[0.26, 0.13, 0.08]}
          >
            <mesh
              geometry={nodes.support4_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[-6.1, 0, 3.55]}
            rotation={[Math.PI / 2, 0, -0.63]}
            scale={[0.31, 0.16, 0.08]}
          >
            <mesh
              geometry={nodes.support5_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.handle3_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[2.75, -0.05, 2.39]}
            rotation={[Math.PI, 0, 0]}
            scale={0.06}
          >
            <mesh
              geometry={nodes.pCylinder13_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[2.94, -0.05, 2.39]}
            rotation={[Math.PI, 0, 0]}
            scale={0.06}
          >
            <mesh
              geometry={nodes.pCylinder14_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[3.29, -0.07, 2.3]}
            rotation={[Math.PI, 0, 0]}
            scale={0.04}
          >
            <mesh
              geometry={nodes.pCylinder15_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[2.99, -0.07, 2.75]}
            rotation={[Math.PI, 0, 0]}
            scale={0.04}
          >
            <mesh
              geometry={nodes.pCylinder16_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[3.28, -0.08, 2.7]}
            rotation={[Math.PI, 0, 0]}
            scale={0.04}
          >
            <mesh
              geometry={nodes.pCylinder17_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[3.52, -0.06, 2.61]}
            rotation={[Math.PI, 0, 0]}
            scale={0.04}
          >
            <mesh
              geometry={nodes.pCylinder18_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[3.84, -0.08, 2.32]}
            rotation={[Math.PI, 0, 0]}
            scale={0.04}
          >
            <mesh
              geometry={nodes.pCylinder19_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[6.36, -0.08, 2.26]}
            rotation={[Math.PI, 0, 0]}
            scale={0.03}
          >
            <mesh
              geometry={nodes.pCylinder20_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[6.79, -0.08, 2.24]}
            rotation={[Math.PI, 0, 0]}
            scale={0.03}
          >
            <mesh
              geometry={nodes.pCylinder21_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[6.36, -0.08, 2.45]}
            rotation={[Math.PI, 0, 0]}
            scale={0.03}
          >
            <mesh
              geometry={nodes.pCylinder22_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.top_blade3_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.pCube7_lambert3_0.geometry}
              material={materials.lambert3}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.oval_hole3_lambert4_0.geometry}
              material={materials.lambert4}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 1.03]}>
            <mesh
              geometry={nodes.handle4_lambert3_0.geometry}
              material={materials.lambert3}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.holes4_lambert4_0.geometry}
              material={materials.lambert4}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/katana.gltf");
