/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Daniel (https://sketchfab.com/DanielAndersson)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/star-wars-tie-interceptor-80171ec2930b4949836bcf24d9694c41
title: Star Wars: TIE Interceptor
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/starwars-ship.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={10}>
        <group scale={0.08}>
          <mesh
            geometry={nodes.ArmGreebles_0.geometry}
            material={materials.ScratchedMetal}
          />
        </group>
        <mesh
          geometry={nodes.ArmPlates_0.geometry}
          material={materials.ScratchedMetal}
        />
        <mesh
          geometry={nodes.Arms_0.geometry}
          material={materials.ScratchedMetal}
        />
        <mesh
          geometry={nodes.Arms_1.geometry}
          material={materials.ScratchedMetalDark}
        />
        <group position={[0, 0.14, 0]}>
          <mesh
            geometry={nodes.Engines_0.geometry}
            material={materials.ScratchedMetal}
          />
          <mesh
            geometry={nodes.Engines_1.geometry}
            material={materials.RedEngineGlow}
          />
        </group>
        <group position={[0, 0.11, 0.07]}>
          <mesh
            geometry={nodes.CockpitGreebles_0.geometry}
            material={materials.ScratchedMetal}
          />
        </group>
        <group position={[0, 0.14, 0]}>
          <mesh
            geometry={nodes.EngineGreebles_0.geometry}
            material={materials.ScratchedMetal}
          />
        </group>
        <mesh
          geometry={nodes.HullPlates_0.geometry}
          material={materials.ScratchedMetal}
        />
        <mesh
          geometry={nodes.MainHull_0.geometry}
          material={materials.ScratchedMetal}
        />
        <mesh
          geometry={nodes.MainHull_1.geometry}
          material={materials.ReflectiveGlass}
        />
        <mesh
          geometry={nodes.MainHull_2.geometry}
          material={materials.ScratchedMetalDark}
        />
        <mesh
          geometry={nodes.Wings_0.geometry}
          material={materials.ScratchedMetal}
        />
        <mesh
          geometry={nodes.Wings_1.geometry}
          material={materials.TieWingMesh}
        />
        <mesh geometry={nodes.Wings_2.geometry} material={materials.Black} />
        <group position={[0, 0.11, 0.07]}>
          <mesh
            geometry={nodes.Window_0.geometry}
            material={materials.ReflectiveGlass}
          />
          <mesh
            geometry={nodes.Window_1.geometry}
            material={materials.ScratchedMetalDark}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/starwars-ship.gltf");
